"""add_users_email_and_pwd

Revision ID: ac79d00ee518
Revises: 003_remove_constraint
Create Date: 2025-10-19 17:20:49.466412

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac79d00ee518"
down_revision = "003_remove_constraint"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("phone_number", sa.String(length=20), nullable=True)
    )
    op.add_column("users", sa.Column("password", sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
