"""telegram_id_optional

Revision ID: c2a98e5201cb
Revises: ac79d00ee518
Create Date: 2025-10-19 21:53:03.885958

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2a98e5201cb"
down_revision = "ac79d00ee518"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "telegram_user_id", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "telegram_user_id", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
